# Generated by Django 3.1.1 on 2024-01-08 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProjects',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('company_mail', models.CharField(blank=True, max_length=255, null=True)),
                ('company_phone', models.CharField(blank=True, max_length=255, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('intervar_mail_sends', models.CharField(max_length=255)),
                ('max_mail_sends', models.IntegerField()),
                ('email_title', models.CharField(blank=True, max_length=255, null=True)),
                ('email_subject', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.companyprojects')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyAnaliticsMail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('count_sends_mail', models.IntegerField()),
                ('count_anmswer_mail', models.IntegerField()),
                ('count_open_mail_on_company', models.IntegerField()),
                ('count_aveible_interval', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.companyprojects')),
                ('company_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.companysettings')),
            ],
        ),
    ]
